### ISSUE TITLE
use of pin 33

### ISSUE THREAD

**Issue by B-Laurent** [kingyoPiyo/Tang-Nano_100BASE-FX_Talker#1]
Hello, 

One question about the adc part of circuit.

There is no declaration about the pin 33 it in the file sfp_tx.cst.
Could you enlighten me about it ?

Thank for help

**Comment by kingyoPiyo** [comment]
Hello.

Pin 34 and pin 33 are a differential pair of LVDS.
Pin 34 is a positive input and pin 33 is a negative input.

When pin 34 is set to LVDS25, pin 33 of the pair is automatically assigned.

**Comment by B-Laurent** [comment]
Hello,
Thank you for these clarifications
Have a good day

LAurent_B
